name: branch-naming-rules
description: "A GitHub Action which prevents pull requests from being merged and sends issue notifications."

inputs:
  token:
    description: "A personal access token with repo permission."
    required: true
  regex:
    description: "A regex string matching a correct branch naming convention."
    required: true
  app-name:
    description: "Name of the application"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "check-circle"
  color: "blue"
